baseURL: https://www.aivision.app/
languageCode: en-us
title: Abdullah
theme: "PaperMod"
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pagination:
  pagerSize: 5

minify:
  disableXML: true
  minifyOutput: true

pygmentsUseClasses: true
